name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create local package
        run: npm pack

      - name: Create capacitor app and build it
        run: | 
          npm init @capacitor/app temp -- --name temp --app-id temp.com
          cd temp
          npm install
          npm i ../*.tgz
          npm install @capacitor/android
          npx cap add android
          npx cap build android

